/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.boot.SpringApplication;


@SpringBootApplication
@ComponentScan({"common", "application"})
public class App {
    public String getGreeting() {
        return "Hello world 2nd.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    	SpringApplication.run(App.class, args);
    }
}
